image: maven:3.8.3-openjdk-17

stages:
    - build
    - test
    - deploy

build:
    stage: build
    tags: 
        - docker
    script:
        - echo "Maven build started"
        - "mvn clean package"
    artifacts:
        paths:
            - target/*.jar
    only:
        - dev

test:
    stage: test
    script:
        - echo "Maven test started"
        - "mvn verify"

deploy staging:
    stage: deploy
    needs: [build]
    script:
        - echo "Maven deploy to staging started"
        - chmod 600 $SSH_PRIVATE_KEY
        - scp -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no /builds/movie-night-planner-2/mnp1/target/MovieNightPlanner-0.0.1-SNAPSHOT.jar ec2-user@13.52.203.195:/home/ec2-user
        - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no ec2-user@13.52.203.195 "java -jar /home/ec2-user/MovieNightPlanner-0.0.1-SNAPSHOT.jar"
        
    only:
        - dev
