image: maven:3.8.3-openjdk-17

stages:
    - build
    - test
    - deploy

build:
    stage: build
    tags: 
        - docker
    script:
        - echo "Maven build started"
        - "mvn clean package"
    artifacts:
        paths:
            - target/*.jar
    only:
        - dev

test:
    stage: test
    script:
        - echo "Maven test started"
        - "mvn verify"

deploy staging:
    stage: deploy
    needs: [build]
    script:
        - echo "Maven deploy to staging started"
        - chmod 600 $SSH_PRIVATE_KEY
        - scp -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $JAR_FILE $IP_ADDRESS
        - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no $IP_ADDRESS "fuser -k 8080/tcp || true; java -jar /home/ec2-user/MovieNightPlanner-0.0.1-SNAPSHOT.jar > /home/ec2-user/application.log 2>&1 &"
    only:
        - dev
