image: maven:3.8.3-openjdk-17

stages:
    - build
    - test
    - package
    - deploy

build:
    stage: build
    tags:
        - docker
    script:
        - echo "Maven build started"
        - "mvn compile"
    artifacts:
        paths:
            - movie-planner/target
    only:
        - dev

test:
    stage: test
    tags:
        - docker
    script:
        - echo "Maven test started"
        - "mvn --batch-mode test"

package:
    stage: package
    tags:
        - docker
    script:
        - echo "Maven packaging started"
        - "mvn clean package"

deploy:
    stage: deploy
    tags:
        - docker
    script:
        - echo "Maven deploy started"
    only:
        - dev
