image: maven:3.8.3-openjdk-17

stages:
    - build
    - test
    - package
    - deploy

build:
    stage: build
    tags:
        - docker
    script:
        - echo "Maven build started"
        - "mvn clean package"
    only:
        - dev

test:
    stage: test
    tags:
        - docker
    script:
        - echo "Maven test started"
        - "mvn verify"
