image: maven:3.8.3-openjdk-17

stages:
    - build
    - test
    - deploy

build:
    stage: build
    tags: 
        - docker
    script:
        - echo "Maven build started"
        - "mvn clean package"
    artifacts:
        paths:
            - target/
    only:
        - dev
test:
    stage: test
    script:
        - echo "Maven test started"
        - "mvn verify"
        - pwd
